### ISSUE TITLE
Fingerprint Usable via Radialmenu

### ISSUE THREAD

**Issue by 5tratz** [Randolio/randol_fingerprint#3]
Hey Randol, I have been using this for ages, the first version you made and it's great, thanks. I have recently found this new one you rewrote and so I tried it out, but like before I am unable to add it to the radialmenu. This is how I had it before:

                    id = 'fingerscan',
                    title = 'Fingerprint Scan',
                    icon = 'fingerprint',
                    type = 'client',
                    event = 'randol:client:fingerscan',
                    shouldClose = true

And it worked fine, I have tried many ways to do the same with this new version but cant, can you help?!

Thanks.

**Comment by Randolio** [comment]
Hey, this was rewritten and now only uses the tablet item. You would have to change the code yourself to make it work with radial menu.

**Comment by 5tratz** [comment]
> Hey, this was rewritten and now only uses the tablet item. You would have to change the code yourself to make it work with radial menu.

Yea I noticed it has changed to (policetablet) instead of (fingerscan), I have tried all but it just wont work. I even tried to add this:

RegisterNetEvent('randol_fingerprint:client:ToggleFingerscan', function()
  local item = QBCore.Functions.HasItem('fingerscan')
  if item then toghud = not toghud end
end)

To see if that would work, but nope :|
